POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "shakeel",
    "email": "shakeelanver26@gmail.com",
    "password": "1234"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "shakeelanver26@gmail.com",
    "password": "1234"
}