POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "raman",
    "email": "raman26@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "raman26@gmail.com",
    "password": "123456"
}

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "email": "raman26@gmail.com",
    "password": "123456"
}
